import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from './components/Navbar';
import Footer from './components/Footer';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export const URL_API = "http://localhost:1337";

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${inter.className} bg-gray-100`}>
				<Navbar icon={""} facebook={"https://www.facebook.com/hoang3409"} instagram={"https://www.instagram.com/?hl=en"} />
				<div className="max-w-[1200px] m-auto">
					{children}
					<Footer />
				</div>
			</body>
		</html>
	);
}
